# Generated by Django 4.0 on 2021-12-27 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('UUID', models.UUIDField(default=uuid.UUID('8c14eaaa-2c22-4358-82a3-5a6c17f294b2'), editable=False,
                                          primary_key=True, serialize=False)),
            ],
        ),
    ]
