# Generated by Django 4.0 on 2021-12-29 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='uname',
        ),
        migrations.AlterField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.UUID('21888266-a32d-4647-855f-88c62a5ae85d'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
