# Generated by Django 4.0 on 2021-12-29 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_user_uname_alter_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='e_mail',
        ),
        migrations.AlterField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.UUID('124d8adc-b101-4b9b-8ee3-4b696d94f177'), editable=False, primary_key=True, serialize=False),
        ),
    ]
