# Generated by Django 4.0.1 on 2022-01-18 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=32, unique=True)),
                ('repo', models.URLField(blank=True)),
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('authors', models.ManyToManyField(to='users.User')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('text', models.TextField()),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('upd_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.project')),
            ],
            options={
                'ordering': ['cr_date'],
            },
        ),
    ]
